Improve the dummy country to enable more tests on variable API
openfisca/openfisca-dummy-country pull request #6
Opened 2017-04-26 09:14 UTC by fpagnoux

Connected to openfisca/openfisca-web-api#125

2017-04-28 14:09 UTC, MattiSG requested changes

2017-04-28 14:09 UTC, MattiSG commented on openfisca_dummy_country/model/model.py
> +    def function_1880(individu, period, legislation):
> Why do we go back in time so much? This is fun, but might be misleading for new users not understanding the actual scope of OpenFisca.

2017-04-28 14:09 UTC, MattiSG commented on openfisca_dummy_country/model/model.py
> +    label = u"Allocationd pour Parent Isolé"
Typo.

2017-04-28 14:09 UTC, MattiSG commented on openfisca_dummy_country/model/model.py
> +    @dated_function(datetime.date(2000, 1, 1), datetime.date(2009, 12, 31))
Inconsistency: later, this is used as `start = `, and here the parameters are only indexed.

2017-05-03 12:29 UTC, fpagnoux commented on openfisca_dummy_country/model/model.py
> +    @dated_function(datetime.date(2000, 1, 1), datetime.date(2009, 12, 31))
👍

2017-05-03 12:37 UTC, fpagnoux commented on openfisca_dummy_country/model/model.py
> +    def function_1880(individu, period, legislation):
There was a bug with pre-1900 dates. Should this not be tested ?

2017-05-03 13:17 UTC, MattiSG commented on openfisca_dummy_country/model/model.py
> +    def function_1880(individu, period, legislation):
Ok, but perhaps not with so many, so as not to be misleading.

2017-05-03 13:17 UTC, MattiSG approved these changes

2017-05-03 16:04 UTC, merged